### ISSUE TITLE
Version of the Smart M600 macro as a nozzle change macro?

### ISSUE THREAD

**Issue by rawlus** [rootiest/zippy-klipper_config#11]
I’m not yet that proficient at writing macros with lots of variables passed,  but the thought crossed my mind that the way your great smart M600 raises z up high and parks the tool head to hold temp.. with a few variable adjustments could be adapted to a great nozzle change macro..

1. heat hotend if not at set temp for nozzle change
2. retract/unload material if present
3. raise z to max, x to middle, send y bed back to limit
4. hold temp
5. resume after pause after nozzle changed
6. load new filament
7. end nozzle change

i’m going to try and figure it out but it’ll take me some time…. putting the idea out there in the event there’s interest from others.

cheers.

**Comment by rootiest** [comment]
Not a bad idea!

I'll see what I can throw together, check back here later!
I will update you when I have something functional.

**Comment by rootiest** [comment]
Hey, sorry it took me so long to get this done!

I just pushed a commit that adds a `NOZZLE_CHANGE` macro: https://github.com/rootiest/zippy-klipper_config/commit/1254240fc82d263a3894f3d4a2dfde6471000ea2

The new functions are documented here: [Smart Filament Change documentation: Nozzle Change](https://github.com/rootiest/zippy-klipper_config/tree/master/extras/filament_change#nozzle-change)

By default it will park in the center of the XYZ axes. But that can be configured to fit your own personal needs.

Try it out and let me know what you think!

I'm going to leave this issue open until you and/or some others can verify it's working for everyone.

**Comment by rawlus** [comment]
very cool.  i’ll give this one a try and report back. give me a few days i’m traveling at the moment.  cheers.

**Comment by rootiest** [comment]
Alright I am going to go ahead and close this issue as completed.

Thanks for the idea! 👍
