### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by DaVinci-10** [rootiest/zippy-klipper_config#13]
**Is your feature request related to a problem?Add [smart_effector] support to get_probe_limits macro**
I use the [smart_effector] in my printer.cfg, when running this it errored out on get_probe_limits
```
10:40:01 $ GET_PROBE_LIMITS
10:40:01 echo: Failed to detect probe in configfile
```
So I added the following in the macro.

```    
{% elif config["smart_effector"] %}
# smart_effector probe section found
{% set probe = config["smart_effector"] %}
{% set has_probe = True %}
```

And it then functioned properly.
```
10:41:46 $ GET_PROBE_LIMITS
10:41:46 echo: Configured Probe X-Offset -5.00
10:41:46 echo: Configured Probe Y-Offset 0.00
10:41:46 echo: Configured Probe Z-Offset -0.1
10:41:46 echo: Minimum PROBE position X=-9.0 Y=-5.0
10:41:46 echo: Maximum PROBE position X=228.125 Y=212.125
```
**Describe the solution you'd like**
I am not familiar with adding this via pulls or anything, but found it useful. And wanted to let you know somehow or another.
So forgive if would be better another meathod.

**Describe alternatives you've considered**
I can use the [probe] definition on my system, but prefer [smart_effector] as it lets me set probe move acceleration
It would be handy to see other output related to the [smart_effector] features, but not required for the fix.

**Additional context**

**Checklist**

- [x ] I have included a clear description of the feature
- [x ] I have included a description of the solution
- [x ] I have included any alternative solutions or features I've considered
- [x ] I have included any relevant screenshots or videos

**Comment by rootiest** [comment]
Hey @DaVinci-10 this is a great idea!

I will see if I can figure out the relevant config sections to reference and try to add the smart_effector support as well.

I will update here if/when I get something working!

**Comment by rootiest** [comment]
Hey @DaVinci-10 this is a great idea!

I will go ahead and merge in your suggested changes, thank you for the suggestion!

**Comment by rootiest** [comment]
Added in the following commit:

https://github.com/rootiest/zippy-klipper_config/commit/f8d7998904504120151bbfff5510cad19d2e31f7

Thanks @DaVinci-10 !
