### ISSUE TITLE
missing macro

### ISSUE THREAD

**Issue by cdedwards** [rootiest/zippy-klipper_config#2]
SET_TEMPERATURE_FAN_TARGET macro is used but never defined as a macro anywhere. Might be in the missing printer.cfg

**Comment by cdedwards** [comment]
found out why

**Comment by rootiest** [comment]
Yeah that's a [native Klipper command](https://www.klipper3d.org/G-Codes.html#set_temperature_fan_target) (assuming you have a `temperature_fan` defined)
