### ISSUE TITLE
canbus on skr pico error 

### ISSUE THREAD

**Issue by raptordemon** [rootiest/zippy-klipper_config#3]
hi there, thanks for the write up. i followed all the insructions and i get the following error:

sudo ip link set up can0 type can bitrate 500000

output : Cannot find device "can0"

any ideas what i did wrong?

**Comment by rootiest** [comment]
That generally indicates the OS can't see any CAN networks.

My guess is something went wrong with the firmware flash, or the Pico is not powered on.

I need to update the screenshots as there is now an additional line in the menuconfig for RP2040 devices.

It should be set like below:

    Bootloader Offset (No Bootloader)

The bootloader offset should only be used if you have _already_ flashed the device with Canboot **first**, which is a little outside the scope of my guide. Flashing canboot on a usb-canbridge device is still pretty finicky at this time and not something I would recommend for the new users this guide was targeted at.

----

If not any of that then it may be some other issue with the OS configuration.

What do you get when you run:

    cat /etc/network/interfaces.d/can0

It should look like this:

    allow-hotplug can0
    iface can0 can static
        bitrate 1000000
        up ifconfig $IFACE txqueuelen 1024

**Comment by raptordemon** [comment]
i ended up returning this board and bought a manta and everything is working
