### ISSUE TITLE
Include [beacon] in GET_PROBE_LIMITS macro

### ISSUE THREAD

**Issue by DrFate09** [rootiest/zippy-klipper_config#9]
With the recent launch of the Beacon inductive sensor, their documentation requires the removal of the [probe] section and the usage of [beacon] instead.

Can we update the GET_PROBE_LIMITS macro to also include [beacon]? Currently, it errors out with the message "No probe or bltouch sections found".

Documentation: https://docs.beacon3d.com/quickstart/

**Comment by rootiest** [comment]
I can give it a shot.

I don't personally own one to test with, and I don't believe it's supported natively so that may pose a problem.

I will throw something together and send it to you if you wanna test it.

My main concern is that I need to be able to query the beacon config values through the printer object. 

Every native feature supports this function, but it's sometimes left out of non-native addons like this beacon config.

Give me an hour or so and I will put together an initial draft and someone who owns a beacon can give it a try.

**Comment by rootiest** [comment]
[Here's a test release](https://gist.github.com/rootiest/1f68250f9d72fea16ed325ece91c06b7)

If you are able to test it out for me and it works we can push it to the main repo.

**Comment by DrFate09** [comment]
![image](https://user-images.githubusercontent.com/22684695/226213127-e79a2f6c-8121-428c-a666-a6805b8b80ba.png)

Here are the results on my Beacon equipped printer. All of the results are valid and I was able to generate a bed mesh from the minimum and maximum values. The only lingering question is the Z-Offset result. Looking at my printer.cfg, there isn't a clear indicator of a Z-offset. I think the Beacon stores it in another way than how it is traditional done. 

![image](https://user-images.githubusercontent.com/22684695/226213337-e741a250-62bf-4751-9acb-c7f6126a42ef.png)

**Comment by rootiest** [comment]
> there isn't a clear indicator of a Z-offset. I think the Beacon stores it in another way than how it is traditional done.

Ah, you are correct, I overlooked that.

Looking at the config in the docs you linked, it doesn't have a z_offset value. It also doesn't appear to need one based on what I can gather of how it works.

So I'm think I can just have it skip that line for beacon probes, does that sound good?

I'm open to pulling another value as well, maybe trigger_distance?

Let me know what you think and I will merge it in. :)

**Comment by rootiest** [comment]
[Here is a version that tries to use trigger_distance instead](https://gist.github.com/rootiest/79443bc72f3a161fb6cb86ee2eae7b47)

**Comment by DrFate09** [comment]
![image](https://user-images.githubusercontent.com/22684695/226215393-15802e4b-5f91-4fcd-9371-fba18fc9403b.png)

Sounds good to me!

**Comment by rootiest** [comment]
Ok great! 👍 

I will push it to the repo and close this issue then.

Thanks for the suggestion! :)

**Comment by rootiest** [comment]
[Commit](https://github.com/rootiest/zippy-klipper_config/commit/69d20d4efb6dfbe1131deeb782670e6a74ce8029)
